version: '3.8'

services:
  app:
    image: node:20
    container_name: my-node-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    environment:
      MONGO_URI: ${MONGO_URI}
    command: ['npm', 'start']

networks:
  default:
    external:
      name: mongo
